# Generated by Django 2.0 on 2020-03-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_processo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadprocesso',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cadprocesso',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cadprocesso',
            name='enviado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
